name: Deploy frontend

on:
  push:
    branches:
      - main

    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-release.yml'
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive

  lint-types:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Lint by tsc
        run: yarn lerna run --scope frontend lint:types

  lint-script:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Lint by ESLint
        run: yarn lerna run --scope frontend lint:script

  lint-style:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Lint by Stylelint
        run: yarn lerna run --scope frontend lint:style

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ matrix.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v1
      #   with:
      #     envkey_VITE_BASE_URL: ${{ secrets.BASE_URL }}
      #     envkey_VITE_API_KEY: ${{ secrets.API_KEY }}
      #     envkey_VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      #     envkey_VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      #     envkey_VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      #     envkey_VITE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
      #     envkey_VITE_APP_ID: ${{ secrets.APP_ID }}
      #     envkey_VITE_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      - name: Build
        run: yarn lerna run --scope frontend build

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: frontend/dist

  deploy:
    needs: [lint-types, lint-script, lint-style, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: frontend/dist

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOROGUE }}'
          channelId: live
          projectId: blorogue
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
